export const SET_COURSE_LIST = 'SET_COURSE_LIST'
export const SET_INTRODUCE_LIST = 'SET_INTRODUCE_LIST'
export const SET_INTRODUCE_TOTAL = 'SET_INTRODUCE_TOTAL'
export const SET_MODAL_TEACHER = 'SET_MODAL_TEACHER'
