// role-management
export const SET_ROLE_LIST = 'SET_ROLE_LIST'
export const SET_MODAL_SHOW = 'SET_MODAL_SHOW'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
export const SET_ROLE_TREE_VIEW = 'SET_ROLE_TREE_VIEW'
export const SET_ROLE_TREE_CHECKED_CHANGE_LIST =
  'SET_ROLE_TREE_CHECKED_CHANGE_LIST'
export const SET_TREE_INIT = 'SET_TREE_INIT'
export const SET_ACCOUNT_LIST = 'SET_ACCOUNT_LIST'
