export const SET_MANAGERLIST = 'SET_MANAGERLIST'
export const SET_MODAL_RELATE = 'SET_MODAL_RELATE'
export const SET_CURRENT_SCHOOL_ADMINISTRATOR =
  'SET_CURRENT_SCHOOL_ADMINISTRATOR'
export const RESET_CURRENT_SCHOOL_ADMINISTRATOR =
  'RESET_CURRENT_SCHOOL_ADMINISTRATOR'
export const SET_SALES_LIST = 'SET_SALES_LIST'
