export const SET_MODAL_RELATE = 'SET_MODAL_RELATE'
export const SET_MYDETAILS_INFO = 'SET_MYDETAILS_INFO'
export const SET_PASSWORD_MODAL = 'SET_PASSWORD_MODAL'
export const SET_IMAGE_RELATE = 'SET_IMAGE_RELATE'
