// school-enterprise-management
export const SET_ACCOUNT_LIST_DATA = 'SET_ACCOUNT_LIST_DATA'
export const SET_CURRENT_SCHOOL_DATA = 'SET_CURRENT_SCHOOL_DATA'
export const RESET_CURRENT_SCHOOL_DATA = 'RESET_CURRENT_SCHOOL_DATA'
